name: Firebase Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2
      - name: Install Dependencies
        run: npm install
        working-directory: frontend
      # - name: Run Tests
      #   env:
      #     CI: true
      #   run: npm test --passWithNoTests
      #   working-directory: frontend
      - name: Build
        run:  npm run build
        working-directory: frontend
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
  deploy:
    name: Deploy
    needs: build
    # on:
    #   push:
    #     branches:
    #       - main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        
      - run: npm install
        working-directory: frontend
      - run: npm run build
        working-directory: frontend
      # - name: Set project dir environment var
      #   run: echo ::set-env name=PROJECT_DIR::"$GITHUB_WORKSPACE/frontend"
      - uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_DIR: ./frontend
          # PROJECT_PATH: "$GITHUB_WORKSPACE/frontend"